### ISSUE TITLE
[FEAT] 팀의 CRUD 기능을 구현한다.

### ISSUE THREAD

**Issue by amaran-th** [BDD-CLUB/01-doo-re-back#13]
## 💬 기능 내용

Team 생성, 조회, 수정, 삭제 기능을 구현한다. 
아직 세부사항이 논의되지 않은 생성, 수정, 삭제의 경우 임시로 구현하도록 하고, 추후 API 명세가 확정되면 수정하도록 한다.

## 📝 작업 내용

- [x] 팀 생성 api 구현
- [x] 팀 수정 api 구현
- [ ] 팀 조회 api 구현
- [x] 팀 삭제 api 구현
- [ ] 팀 삭제 시 연관된 스터디, 커리큘럼 삭제 기능 구현

## ⏰ 예상 소요 시간 (선택)

~~21일까지 해보겠습니다.~~

## 📁 참고 자료 (선택)

[두레 사용자 스토리 맵](https://www.figma.com/file/QODxwOkHC18QqWcr7xVLxy/%EB%91%90%EB%A0%88---%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%8A%A4%ED%86%A0%EB%A6%AC-%EB%A7%B5?type=whiteboard&node-id=0-1&t=R0I9SS9cH5ZDcoue-0)

**Comment by shkisme** [comment]
팀 상세 정보 조회 기능은 스터디 파트까지 완료되고 나면 작업하도록 하겠습니다.
