### ISSUE TITLE
[REFACTOR] HTTP 메서드 테스트용 코드 분리

### ISSUE THREAD

**Issue by lcqff** [BDD-CLUB/01-doo-re-back#60]
## 💬 리팩터링 내용

디스커션 참고: https://github.com/BDD-CLUB/01-doo-re-back/discussions/59#discussion-6146569

## ⚡️ AS-IS

`RestDocsTest`와 `IntegrationTest`에 동일한 커스텀 HTTP 메서드 테스트용 코드가 중복해서 존재

## ⭐️ TO-BE

중복되는 커스텀 HTTP 메서드 코드를  **ApiTestHelper**라는 클래스로 분리 후 `RestDocsTest`와 `IntegrationTest`에 상속

## ⏰ 예상 소요 시간 (선택)

1시간 내

**Comment by shkisme** [comment]
#71 에서 해결
